name: ScaleUp Breakfast Club
favicon: null
layout_spectrum: 0.29056497011333704
typography_spectrum: 0.5979690400417894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6301436792127788
  lightness: 0.755359701346606
  saturation: 0.7928701008204371
  rhythmicContrast: 0.1768169067800045
purpose: []
